// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eSWE-7MUd_L6ipbMNkeqt_yXRZnjEb4',
    appId: '1:522176211793:web:e153775c47662e36f34170',
    messagingSenderId: '522176211793',
    projectId: 'foodchoose-4f82e',
    authDomain: 'foodchoose-4f82e.firebaseapp.com',
    storageBucket: 'foodchoose-4f82e.firebasestorage.app',
    measurementId: 'G-V4WPFY0JYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9O7N5R5LH-MMeINGy6tTM-XUwa7O2Pzs',
    appId: '1:522176211793:android:7a4eeb2d9ac9b12df34170',
    messagingSenderId: '522176211793',
    projectId: 'foodchoose-4f82e',
    storageBucket: 'foodchoose-4f82e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSPMXejfhZ8B-OyMypTYRK2vvB97ly0E',
    appId: '1:522176211793:ios:14aa78498ef5bf64f34170',
    messagingSenderId: '522176211793',
    projectId: 'foodchoose-4f82e',
    storageBucket: 'foodchoose-4f82e.firebasestorage.app',
    iosBundleId: 'com.example.foodchoose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSPMXejfhZ8B-OyMypTYRK2vvB97ly0E',
    appId: '1:522176211793:ios:14aa78498ef5bf64f34170',
    messagingSenderId: '522176211793',
    projectId: 'foodchoose-4f82e',
    storageBucket: 'foodchoose-4f82e.firebasestorage.app',
    iosBundleId: 'com.example.foodchoose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5eSWE-7MUd_L6ipbMNkeqt_yXRZnjEb4',
    appId: '1:522176211793:web:12f0c60df555d055f34170',
    messagingSenderId: '522176211793',
    projectId: 'foodchoose-4f82e',
    authDomain: 'foodchoose-4f82e.firebaseapp.com',
    storageBucket: 'foodchoose-4f82e.firebasestorage.app',
    measurementId: 'G-0LHR17NMQV',
  );
}
